# Generated by Django 5.0.6 on 2026-03-19 00:27

from django.db import migrations


def populate_dashboard_types(apps, schema_editor):
    DashboardType = apps.get_model('core', 'DashboardType')
    types = [
        'Financeiro',
        'Médico / Saúde',
        'FreshService',
        'Recursos Humanos',
        'Operacional',
        'Gestão de TI',
    ]
    for type_name in types:
        DashboardType.objects.get_or_create(name=type_name)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dashboardtype_dashboard_dashboard_type'),
    ]

    operations = [
        migrations.RunPython(populate_dashboard_types),
    ]
