# Generated by Django 5.0.6 on 2026-03-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_dashboard_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dashboardtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
    ]
