# Generated by Django 5.0.6 on 2026-03-19 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dashboard_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='specific_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardtype',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
