# Generated by Django 5.0.6 on 2026-03-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dashboard_allowed_users_dashboardtype_allowed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='dashboard_type',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='dashboard_types',
            field=models.ManyToManyField(blank=True, related_name='dashboards', to='core.dashboardtype'),
        ),
    ]
