# Generated by Django 5.0.6 on 2026-03-19 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_dashboard_dashboard_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardtype',
            name='allowed_users',
        ),
    ]
