# Generated by Django 5.0.6 on 2026-03-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_auditlog_action_remove_auditlog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='dashboard_types',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to='core.dashboardtype'),
        ),
    ]
