# Generated by Django 5.0.6 on 2026-03-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtype',
            name='color',
            field=models.CharField(default='#64748b', help_text='Cor hexadecimal para a categoria', max_length=7),
        ),
    ]
