# Generated by Django 5.0.6 on 2026-03-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dashboardtype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('Inserção', 'Inserção'), ('Edição', 'Edição'), ('Remoção', 'Remoção'), ('Falha de Login', 'Falha de Login')], default='Edição', max_length=20),
        ),
    ]
